projects:
  todo:
    schemaPath: src/graphql/schema.json
    includes:
      - ./src/graphql/**/*.ts
    excludes:
      - ./src/amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: ./src/API.ts
        docsFilePath: src/graphql
