[package]
name = "rvemu-for-book"
version = "0.1.0"
authors = ["touyou <fujiyou1121@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
